name: CI/CD

on:
  push:
    branches:
      - master  # 또는 main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: CloudType에 배포
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}  # 미리 등록한 API Key
          project: api                           # cloudtype.yaml 에 정의된 프로젝트 이름
          stage: master                          # 배포할 스테이지 이름 (cloudtype.yaml 안에 설정되어 있어야 함)
          file: cloudtype.yaml                   # 배포 설정 파일 경로
