name: Deploy to CloudType

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CloudType CLI
        run: npm install -g @cloudtype/cli

      - name: Deploy to CloudType
        run: ct deploy -t ${{ secrets.CLOUDTYPE_TOKEN }}